package com.brosh.finance.monthlybudgetsync.config;

public class Definitions {
    public static final String CATEGORIES = "categories";// todo replace name to Categories
    public static final String TRANSACTIONS = "transactions";
    public static final String MONTHLY_BUDGET = "Monthly Budget";
    public static final String BUDGETS = "Budget";// todo replace name to Budgets
    public static final String MONTHS = "Months";
    public static final String MONTH = "Month";
    public static final String SHOPS = "Shops";
    public static final String ZERO = "0";
    public static final String DOT = ".";
    public static final String COMMA = ",";
    public static final String ARROW_RIGHT = "->";
    public static final char ARROW_UP = 'ꜛ';
    public static final char ARROW_DOWN = 'ꜜ';
    public static final String HEBREW = "HEB";
    public static final String ENGLISH = "EN";
    public static final String DASH = "-";
    public static final String BALANCE = "balance";
    public static final String BUDGET = "budget";
    public static final String NAME = "name";
    public static final String DELETED = "deleted";
    public static final String BUDGET_NUMBER = "budgetNumber";
    public static final String TRAN_ID_NUMERATOR = "tranIdNumerator";
    public static final String SHARES = "Shares";
    public static final String USERS = "Users";
    public static final String USER = "User";
    public static final String EMAIL_ALREADY_SHARED = "Email already shared";
    public static final String CREATE_CODE = "CRT";
    public static final String ADD_CODE = "ADD";
    public static final String DELETE_CODE = "DEL";
    public static final String USER_SETTINGS = "userSettings";
    public static final String CONTACT_US = "contactUs";
    public static String dbKey = "dbKey";
    public static final int SORT_BY_ID = 1;
    public static final int SORT_BY_CATEGORY = 2;
    public static final int SORT_BY_PAYMRNT_METHOD = 3;
    public static final int SORT_BY_STORE = 4;
    public static final int SORT_BY_CHARGE_DATE = 5;
    public static final int SORT_BY_PRICE = 6;
    public static final int SORT_BY_REGISTRATION_DATE = 7;
    public static String CHARGE_DAY = "chargeDay";
    public static String CURRENCY = "currency";
    public static String DEFAULT_SHOW_ACTIVE_ONLY = "defaultShowActiveOnly";
    public static String AUTO_COMPLETE = "autoComplete";
    public static String EMAIL_UPDATES = "emailUpdates";
    public static String NOTIFICATIONS = "notifications";
}
